package main

import (
  "os"
  "html/template"
  "github.com/otiai10/copy"
  "strings"
  "fmt"
  "errors"
  "path/filepath"
  "bufio"
  "github.com/bankole7782/sites115/sites115s"
  "github.com/russross/blackfriday"
  "math"
  "strconv"
  "github.com/saenuma/zazabul"
  "github.com/gookit/color"
)


type PaginatorStruct struct {
  Page int
  PaginationCount int
  Pages []map[string]string
  TotalPages int
  PreviousPage int
  PreviousPagePath string
  NextPage int
  NextPagePath string
  TotalPagesArr []int
}

type HTMLContext struct {
  Page map[string]string
  Paginator PaginatorStruct
}

func generate(siteName string) {
  rootPath, _ := GetRootPath()

  tmpPath := filepath.Join(rootPath, siteName, "tmp")
  os.RemoveAll(tmpPath)

  copy.Copy(filepath.Join(rootPath, siteName, "site.zconf"), filepath.Join(rootPath, siteName, "out", "site.zconf"))
  // copy statics
  copy.Copy(filepath.Join(rootPath, siteName, "static"), filepath.Join(rootPath, siteName, "out", "static"))
  os.WriteFile(filepath.Join(rootPath, siteName, "static", "index.html"),
    []byte("index.html not generated for this page."), 0777)

  dir := filepath.Join(rootPath, siteName, "stuffs")

  // render pages
  err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
    if err != nil {
      return err
    }

    if info.IsDir() {
      if ! sites115s.DoesPathExists(filepath.Join(path, "index.html")) {
        return errors.New(fmt.Sprintf("The directory '%s' does not have an index.html. It is compulsory", path))
      }
      if ! sites115s.DoesPathExists(filepath.Join(path, "toc.txt")) && path != dir {
        return errors.New(fmt.Sprintf("The directory '%s' does not have an toc.txt . It is compulsory", path))
      }
    }

    if ! info.IsDir() {
      if ! strings.HasSuffix(dir, "/") {
        dir += "/"
      }

      if strings.HasSuffix(path, ".txt") {
        return nil
      }

      raw, err := os.ReadFile(path)
      if err != nil {
        return err
      }
      if ! strings.HasPrefix(string(raw), "---") {
        return errors.New(fmt.Sprintf("The file '%s' does not have a data part", path))
      }

      pathToWrite := strings.Replace(path, dir, "", 1)

      if strings.HasSuffix(path, ".html") {
        return RenderHTMLToFile(string(raw), pathToWrite, siteName)
      } else if strings.HasSuffix(path, ".md") {
        return RenderMDToFile(string(raw), pathToWrite, siteName)
      }

      // outStr := fmt.Sprintf("%s,,,%d\n", pathToWrite, info.Size())
      // indexFile.WriteString(outStr)
    }
    return nil
  })

  if err != nil {
    panic(err)
  }
}


func GetPartsOfMarkup(s string) (string, string) {
  parts := strings.Split(s, "\n")
  var endOfDataIndex int
  for index, part := range parts {
    if index == 0 {
      continue
    }
    if part == "---" {
      endOfDataIndex = index
      break
    }
  }

  dataPart := strings.Join(parts[1: endOfDataIndex], "\n")
  markupPart := strings.Join(parts[endOfDataIndex+1: ], "\n")
  return dataPart, markupPart
}


func ParsePageVariables(s string) map[string]string {
  parts := strings.Split(s, "\n")
  var colonIndex int
  ret := make(map[string]string)
  for _, line := range parts {
    for i, ch := range line {
      if fmt.Sprintf("%c", ch) == ":" {
        colonIndex = i
        break
      }
    }

    if colonIndex == 0 {
      continue
    }

    itemName := strings.ToLower(strings.TrimSpace(line[0: colonIndex]))
    itemValue := strings.TrimSpace(line[colonIndex + 1 : ])
    ret[itemName] = itemValue
  }

  return ret
}


func RenderHTMLToFile(s, path, siteName string) error {
  rootPath, _ := GetRootPath()
  dataPart, markupPart := GetPartsOfMarkup(s)
  pageVariables := ParsePageVariables(dataPart)

  confPath := filepath.Join(filepath.Join(rootPath, siteName, "site.zconf"))

  if ! sites115s.DoesPathExists(confPath) {
    panic("invalid path. its not a path with contents generated by sites115")
  }

  conf, err := zazabul.LoadConfigFile(confPath)
  if err != nil {
    panic(err)
  }

  for _, item := range conf.Items {
    if item.Value == "" {
      color.Red.Println("Every field in the launch file is compulsory.")
      os.Exit(1)
    }
  }


  tmpPath := filepath.Join(rootPath, siteName, "tmp")
  os.MkdirAll(tmpPath, 0777)
  tmpMarkupPath := filepath.Join(tmpPath, "m" + UntestedRandomString(10) + ".html")

  os.WriteFile(tmpMarkupPath, []byte(markupPart), 0777)

  tmpl, err := template.ParseFiles(filepath.Join(rootPath, siteName, "templates", pageVariables["template"]), tmpMarkupPath)
  if err != nil {
    return err
  }

  paginationCount, err := strconv.Atoi(conf.Get("pagination_count"))
  if err != nil {
    return err
  }

  var paginator PaginatorStruct
  tocObj := make([]map[string]string, 0)
  if strings.HasSuffix(path, "index.html") && path != "index.html" {
    tocFile := strings.ReplaceAll(path, "index.html", "toc.txt")
    tocPath := filepath.Join(rootPath, siteName, "stuffs", tocFile)
    rawTocFile, err := os.ReadFile(tocPath)
    if err != nil {
      return err
    }

    lines := strings.Split(string(rawTocFile), "\n")
    for _, line := range lines {
      line = strings.TrimSpace(line)
      if line == "" {
        continue
      }
      tocLinePath := strings.ReplaceAll(tocPath, "toc.txt", line)
      rawTocLinePath, err := os.ReadFile(tocLinePath)
      if err != nil {
        return err
      }

      dataPart, _ := GetPartsOfMarkup(string(rawTocLinePath))
      pageVariables := ParsePageVariables(dataPart)
      tocURL := strings.ReplaceAll(tocLinePath, filepath.Join(rootPath, siteName, "stuffs"), "")
      tocURL = strings.ReplaceAll(tocURL, ".md", "")
      tocURL = strings.ReplaceAll(tocURL, ".html", "")
      pageVariables["url"] = tocURL

      tocObj = append(tocObj, pageVariables)
    }

    totalLinks := len(lines)
    totalPages := math.Ceil( float64(totalLinks) / float64(paginationCount) )

    pagesArr := make([]int, 0)
    for i := 0; i < int(totalPages); i++ {
      pagesArr = append(pagesArr, i+1)
    }
    paginator := PaginatorStruct{TotalPages: int(totalPages), PaginationCount: paginationCount,
      TotalPagesArr: pagesArr}

    for i := 0; i < int(totalPages); i++ {
      newIndex := i + 1

      if i == int(totalPages) - 1 {
        paginator.Pages = tocObj[(i) * paginationCount: ]
      } else {
        paginator.Pages = tocObj[(i) * paginationCount: (i+1) * paginationCount]
      }

      paginator.Page = newIndex

      if i == 0 {
        paginator.PreviousPage = -1
      } else {
        paginator.PreviousPage = i
        paginator.PreviousPagePath = strings.ReplaceAll(path, "index.html", "index" + strconv.Itoa(paginator.PreviousPage) + ".html")
      }

      if i == int(totalPages) - 1 {
        paginator.NextPage = -1
      } else {
        paginator.NextPage = i
        paginator.NextPagePath = strings.ReplaceAll(path, "index.html", "index" + strconv.Itoa(paginator.NextPage) + ".html")
      }

      // generate the index pages
      if newIndex == 1 {
        innerRenderHTMLToFile(path, siteName, HTMLContext{pageVariables, paginator}, tmpl)
      }

      newPath := strings.ReplaceAll(path, "index.html", "index" + strconv.Itoa(newIndex) + ".html")
      innerRenderHTMLToFile(newPath, siteName, HTMLContext{pageVariables, paginator}, tmpl)

    }

  } else {
    innerRenderHTMLToFile(path, siteName, HTMLContext{pageVariables, paginator}, tmpl)
  }


  return nil
}

func innerRenderHTMLToFile(path, siteName string, ctx HTMLContext, tmpl *template.Template) {
  rootPath, _ := GetRootPath()
  baseDir := filepath.Dir(filepath.Join(rootPath, siteName, "out", path))
  os.MkdirAll(baseDir, 0777)
  outPathHandle, _ := os.Create(filepath.Join(rootPath, siteName, "out", path))
  defer outPathHandle.Close()
  writer := bufio.NewWriter(outPathHandle)

  tmpl.Execute(writer, ctx)
  writer.Flush()
}


func RenderMDToFile(s, path, siteName string) error {
  rootPath, _ := GetRootPath()
  dataPart, markupPart := GetPartsOfMarkup(s)
  pageVariables := ParsePageVariables(dataPart)


  tmpl, err := template.ParseFiles(filepath.Join(rootPath, siteName, "templates", pageVariables["template"]),
    filepath.Join(rootPath, siteName, "templates", pageVariables["md_template"]))
  if err != nil {
    return err
  }

  html := string(blackfriday.MarkdownCommon([]byte(markupPart)))

  type Context struct {
    Page map[string]string
    HTML template.HTML
  }

  baseDir := filepath.Dir(filepath.Join(rootPath, siteName, "out", path))
  os.MkdirAll(baseDir, 0777)

  newPath := strings.ReplaceAll(path, ".md", ".html")
  outPathHandle, err := os.Create(filepath.Join(rootPath, siteName, "out", newPath))
  if err != nil {
    return err
  }
  defer outPathHandle.Close()
  writer := bufio.NewWriter(outPathHandle)

  tmpl.Execute(writer, Context{pageVariables, template.HTML(html)})
  writer.Flush()
  return nil
}
