package main

import (
  "fmt"
  "os"
  "path/filepath"
  "sort"
  "strings"
  "time"
  "github.com/PuerkitoBio/goquery"
  "github.com/bankole7782/sites115/sites115s"
  "github.com/saenuma/zazabul"
  "github.com/adam-hanna/arrayOperations"
)

var visitedLinksMap map[string]bool

func init() {
  visitedLinksMap = make(map[string]bool)
}

type url struct {
  Loc string
  Lastmod string
}

func generateSitemap(sitePath string) {
  confPath := filepath.Join(sitePath, "site.zconf")

  if ! sites115s.DoesPathExists(confPath) {
    panic("invalid path. its not a path with contents generated by sites115")
  }

  conf, err := zazabul.LoadConfigFile(confPath)
  if err != nil {
    panic(err)
  }

  baseURL := conf.Get("base_url")

  trueSitePath := filepath.Join(sitePath, "out")

  links := findAllLinks(trueSitePath, "/")
  // first level
  for _, link := range links {
    tmpLinks := findAllLinks(trueSitePath, link)
    links = append(links, tmpLinks...)
  }
  // second level
  for _, link := range links {
    tmpLinks := findAllLinks(trueSitePath, link)
    links = append(links, tmpLinks...)
  }

  links = arrayOperations.DistinctString(links)
  sort.Strings(links)

  // make xml
  xml := `<?xml version="1.0" encoding="UTF-8"?>
<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
`
  for _, link := range links {
    xml += "  <url>\n    <loc>" + baseURL + link + "</loc>\n"
    xml += "    <lastmod>" + time.Now().Format("2006-01-02T15:04:05+00:00")  + "</lastmod>\n  </url>\n"
  }
  xml += "\n</urlset>"

  os.WriteFile(filepath.Join(sitePath, "out", "static", "sitemap.xml"), []byte(xml), 0777)
}


func findAllLinks(sitePath, path string) []string {
  filePath := path

  if strings.HasSuffix(path, "/") {
    filePath = path + "index.html"
  } else {
    filePath = path + ".html"
  }

  status, found := visitedLinksMap[path]
  if found && status == true {
    return []string{}
  }

  rawLinkHtml, err := os.ReadFile(filepath.Join(sitePath, filePath))
  if err != nil {
    fmt.Println("There is a 404 on your page at " + filePath)
    return []string{}
  }

  doc, err := goquery.NewDocumentFromReader(strings.NewReader(string(rawLinkHtml)))
  if err != nil {
    fmt.Println(err)
    return []string{}
  }

  links := make([]string, 0)
  doc.Find("a").Each(func(i int, s *goquery.Selection) {
    href, ok := s.Attr("href")
    if ! ok {
      return
    }

    if strings.HasPrefix(href, "/") && ! strings.HasPrefix(href, "/static/") {
      links = append(links, href)
    }
  })

  visitedLinksMap[path] = true
  return links
}
