package sites115s

import (
  "log"
  "net/http"
  "os"
  "github.com/saenuma/zazabul"
  "fmt"
  "path/filepath"
  "github.com/gookit/color"
  "strings"
  "net/url"
  "github.com/adam-hanna/arrayOperations"
  "sort"
  "strconv"
  "encoding/json"
  "html/template"
  "math"
)


func StartServer(path string) {
  confPath := filepath.Join(filepath.Join(path, "site.zconf"))

  if ! DoesPathExists(confPath) {
    color.Red.Println("invalid path. its not a path with contents generated by sites115")
    os.Exit(1)
  }

  conf, err := zazabul.LoadConfigFile(confPath)
  if err != nil {
    log.Println(err)
  }

  for _, item := range conf.Items {
    if item.Value == "" {
      color.Red.Println("Every field in the launch file is compulsory.")
      os.Exit(1)
    }
  }

  redirectsMap := make(map[string]string)
  if DoesPathExists(filepath.Join(path, "redirects.txt")) {
    rawRedirectsTxt, err := os.ReadFile(filepath.Join(path, "redirects.txt"))
    if err != nil {
      log.Println(err)
    }

    for _, part := range strings.Split(string(rawRedirectsTxt), "\n\n") {
      parts := strings.Split(strings.TrimSpace(part), "\n")
      if len(parts) != 2 {
        continue
      }
      redirectsMap[parts[0]] = parts[1]
    }
  }

  mux := http.NewServeMux()

  mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    log.Println(r.URL)

    if DoesPathExists(filepath.Join(path, "redirects.txt")) {
      returnPath, ok := redirectsMap[r.URL.Path]
      if ok {
        http.Redirect(w, r, returnPath, 301)
        return
      }
    }

    if r.URL.Path == "/search_results" {
      doSearch(path, w, r)
    } else if strings.HasPrefix(r.URL.Path, "/_indexes") || strings.HasPrefix(r.URL.Path, "/_templates") {
      do404(path, w, r)
    } else if strings.HasSuffix(r.URL.Path, "/") && ! strings.HasPrefix(r.URL.Path, "/static") {
      if ! DoesPathExists(filepath.Join(path, r.URL.Path + "index.html")) {
        do404(path, w, r)
      } else {
        http.ServeFile(w, r, filepath.Join(path, r.URL.Path + "index.html"))
      }
    } else if strings.HasSuffix(r.URL.Path, "/") && strings.HasPrefix(r.URL.Path, "/static") {
      http.ServeFile(w, r, filepath.Join(path, "static", "index.html"))
    } else if strings.HasPrefix(r.URL.Path, "/static") {
      http.ServeFile(w, r, filepath.Join(path, r.URL.Path))
    } else {
      if ! DoesPathExists(filepath.Join(path, r.URL.Path + ".html")) {
        do404(path, w, r)
      } else {
        http.ServeFile(w, r, filepath.Join(path, r.URL.Path + ".html"))
      }
    }
  })

  http.ListenAndServe(fmt.Sprintf(":%s", conf.Get("port")), mux)
}


func do404(path string, w http.ResponseWriter, r *http.Request) {
  w.WriteHeader(http.StatusNotFound)
  raw, _ := os.ReadFile(filepath.Join(path, "404.html"))
  fmt.Fprintf(w, string(raw))
}


func doSearch(path string, w http.ResponseWriter, r *http.Request) {
  params, err := url.ParseQuery(r.URL.RawQuery)
  if err != nil {
    do404(path, w, r)
    return
  }

  if r.FormValue("s") == "" {
    do404(path, w, r)
    return
  }
  words := strings.Fields(params["s"][0])

  retIds := make([]string, 0)
  textWeights := make(map[string]int64)
  for _, word := range words {
    word = CleanWord(word)
    if word == "" {
      continue
    }
    if FindIn(STOP_WORDS, word) != -1 {
      continue
    }

    dirFIs, err := os.ReadDir(filepath.Join(path, "_indexes", word))
    if err != nil {
      do404(path, w, r)
      return
    }

    tmpIds := make([]string, 0)
    for _, dirFI := range dirFIs {
      raw, err := os.ReadFile(filepath.Join(path, "_indexes", word, dirFI.Name()))
      if err != nil {
        log.Println(err)
      }

      wordCount, err := strconv.ParseInt(string(raw), 10, 64)
      if err != nil {
        log.Println(err)
      }
      oldWordCount, ok := textWeights[dirFI.Name()]
      if ! ok {
        textWeights[dirFI.Name()] = wordCount
      } else {
        textWeights[dirFI.Name()] = wordCount + oldWordCount
      }
      tmpIds = append(tmpIds, dirFI.Name())
    }

    retIds = append(retIds, tmpIds...)
  }
  retIds = arrayOperations.DistinctString(retIds)

  sort.SliceStable(retIds, func(i, j int) bool {
    x := textWeights[ retIds[i] ]
    y := textWeights[ retIds[j] ]
    return x > y
  })

  // change the links to addresses.
  rawAllPagesMap, err := os.ReadFile(filepath.Join(path, "allpages.json"))
  if err != nil {
    log.Println(err)
    return
  }
  allPagesMap := make(map[string]string)
  err = json.Unmarshal(rawAllPagesMap, &allPagesMap)
  if err != nil {
    log.Println(err)
    return
  }
  foundPages := make([]string, 0)
  tocObj := make([]map[string]string, 0)

  for _, retId := range retIds {
    descPath := filepath.Join(path, "_page_descs", retId + ".json")
    rawDesc, _ := os.ReadFile(descPath)
    pageVariables := make(map[string]string)
    json.Unmarshal(rawDesc, &pageVariables)
    if allPagesMap[retId] == "" {
      continue
    }
    foundPages = append(foundPages, allPagesMap[retId])
    pageVariables["url"] = strings.ReplaceAll(allPagesMap[retId], ".html", "")
    tocObj = append(tocObj, pageVariables)
  }

  // execute the search results to the templates
  confPath := filepath.Join(filepath.Join(path, "site.zconf"))

  conf, err := zazabul.LoadConfigFile(confPath)
  if err != nil {
    log.Println(err)
    return
  }

  paginationCount, err := strconv.Atoi(conf.Get("pagination_count"))
  if err != nil {
    log.Println(err)
    return
  }

  rawSearchResultsTemplate, _ := os.ReadFile(filepath.Join(path, "_templates", "search_results.html"))
  dataPart, _ := GetPartsOfMarkup(string(rawSearchResultsTemplate))
  pageVariables := ParsePageVariables(dataPart)
  cleanSearchResultsPath := filepath.Join(path, "_templates", "clean_search_results.html")

  tmpl, err := template.ParseFiles(filepath.Join(path, "_templates", pageVariables["template"]), cleanSearchResultsPath)
  if err != nil {
    log.Println(err)
    return
  }

  totalLinks := len(foundPages)
  totalPages := math.Ceil( float64(totalLinks) / float64(paginationCount) )

  pagesArr := make([]int, 0)
  pageMapArr := make([]map[string]string, 0)

  paginator := PaginatorStruct{TotalPages: int(totalPages), PaginationCount: paginationCount, Pages: pageMapArr}

  var pageNum int
  if params.Get("p") == "" {
    pageNum = 1
  } else {
    tmpPageNum, _ := strconv.Atoi(params.Get("p"))
    pageNum = tmpPageNum
  }

  paginator.Page = pageNum

  for i := 0; i < int(totalPages); i++ {
    pagesArr = append(pagesArr, i+1)
  }

  if pageNum == int(totalPages) {
    paginator.Pages = tocObj[(pageNum-1) * paginationCount :]
  } else {
    paginator.Pages = tocObj[(pageNum-1) * paginationCount : (pageNum) * paginationCount]
  }

  paginator.TotalPagesArr = pagesArr

  type Context struct {
    Page map[string]string
    Paginator PaginatorStruct
    SearchStr string
    ToLower func(string) string
    ToUpper func(string) string
    ToLongDate func(string) string
    Modulo func(int, int) int
    Plus func(int, int) int
    Minus func(int, int) int
  }

  searchStr := params.Get("s")

  tmpl.Execute(w, Context{pageVariables, paginator, searchStr, ToLower, ToUpper,
    ToLongDate, Modulo, Plus, Minus})
}
