package main

import (
  "os"
  "github.com/gookit/color"
  "path/filepath"
  "github.com/bankole7782/sites115/sites115s"
)


func main() {
  if len(os.Args) != 2 {
    color.Red.Println("Expecting the path to serve its contents")
    color.Red.Println("This path should be rendered from sites115")
    os.Exit(1)
  }

  path := os.Args[1]
  confPath := filepath.Join(filepath.Join(path, "site.zconf"))

  if ! sites115s.DoesPathExists(confPath) {
    color.Red.Println("invalid path. its not a path with contents generated by sites115")
    os.Exit(1)
  }

  sites115s.StartServer(path)
}
