package main

import (
  "log"
  "net/http"
  "os"
  "github.com/bankole7782/sites115/sites115s"
  "github.com/saenuma/zazabul"
  "fmt"
  "path/filepath"
  "github.com/gookit/color"
  "strings"
)

func main() {
  path := os.Args[1]
  confPath := filepath.Join(filepath.Join(path, "site.zconf"))

  if ! sites115s.DoesPathExists(confPath) {
    panic("invalid path. its not a path with contents generated by sites115")
  }

  conf, err := zazabul.LoadConfigFile(confPath)
  if err != nil {
    panic(err)
  }

  for _, item := range conf.Items {
    if item.Value == "" {
      color.Red.Println("Every field in the launch file is compulsory.")
      os.Exit(1)
    }
  }

  mux := http.NewServeMux()

  mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    log.Println(r.URL.Path)
    if strings.HasSuffix(r.URL.Path, "/") && ! strings.HasPrefix(r.URL.Path, "/static") {
      if ! sites115s.DoesPathExists(filepath.Join(path, r.URL.Path + "index.html")) {
        http.ServeFile(w, r, filepath.Join(path, "404.html"))
      } else {
        http.ServeFile(w, r, filepath.Join(path, r.URL.Path + "index.html"))
      }
    } else if strings.HasSuffix(r.URL.Path, "/") && strings.HasPrefix(r.URL.Path, "/static") {
      http.ServeFile(w, r, filepath.Join(path, "static", "index.html"))
    } else if strings.HasPrefix(r.URL.Path, "/static") {
      http.ServeFile(w, r, filepath.Join(path, r.URL.Path))
    } else {
      if ! sites115s.DoesPathExists(filepath.Join(path, r.URL.Path + ".html")) {
        http.ServeFile(w, r, filepath.Join(path, "404.html"))
      } else {
        http.ServeFile(w, r, filepath.Join(path, r.URL.Path + ".html"))
      }
    }
  })

  http.ListenAndServe(fmt.Sprintf(":%s", conf.Get("port")), mux)
}
